---

- hosts: all
  become: true
  tasks:

  - name: Update Ubuntu Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update Rocky Repository Index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Installs apache2 and php packaages for Rocky.
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

