---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: installs apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: PHP support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: Update Repository Index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: installs apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"

  - name: PHP support for Apache
    apt:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"
