---

- hosts: all
  become: true
  pre_tasks:

    - name: Install updates (Rocky)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Rocky"
    
    - name: Perform package upgrades (Ubuntu)
      tags: always
      apt:
        upgrade: "safe"
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:
    
  - name: Install apache and php packages for Ubuntu
    tags: apache, apache2, ubuntu
    apt:
      name:
       - apache2
       - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php packaages for Rocky.
    tags: apache, rocky, httpd
    dnf:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "Rocky"


- hosts: db_servers
  become: yes
  tasks:
  
  - name: Install mariadb package (Rocky)
    tags: rocky, db, mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"
  
  - name: Install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: yes
  tasks:
  
  - name: Install samba package (Rocky)
    tags: samba
    dnf:
      name: samba
      state: latest
    when: ansible_distribution == "Rocky"
  
  - name: Install samba package (Ubuntu)
    tags: samba
    apt:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"
