---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Uninstall apache2 and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

