---

- hosts: all
  become: true
  tasks:

  - name: Uninstall apache and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes

