---

- hosts: all
  become: yes
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update all packages to their latest version.
    apt:
      name: "*"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Upgrade the system (apt dist-upgrade).
    apt:
      upgrade: "dist"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Autoremove packages that are no longer needed.
    apt:
      autoremove: yes
    when: ansible_distribution == "Ubuntu"
