---

- hosts: all
  become: true
  pre_tasks:

    - name: Install updates (Rocky)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Rocky"
    
    - name: Perform package upgrades (Ubuntu)
      tags: always
      apt:
        upgrade: "safe"
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
