---

- hosts: all
  become: true
  tasks:

  - name: Upgrade Specific Packages
    apt:
      name: ubuntu-advantage-desktop-daemon
        - gnome-remote-desktop
        - python-apt-common
        - python3-apt
        - python3-software-properties
        - software-properties-common
        - software-properties-gtk
        - update-notifier-common
        - update-notifier
        - shim-signed
        - grub-efi-amd64-bin
        - grub-efi-amd64-signed
        - fwupd-signed
      state: latest
    when: ansible_distribution == "Ubuntu"

